### ISSUE TITLE
Support for 4.x/5.x?

### ISSUE THREAD

**Issue by markus138** [NetOxygen/node-qrcodeine#3] opened 2016-03-28 13:52 UTC
Hello, I'm trying to use the library os linux (ubuntu) and mac os and fail with the exception

> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:87:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
> gyp ERR! System Linux 3.19.8-xen
> gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/itnuser/node_modules/qrcodeine
> gyp ERR! node -v v4.4.1
> gyp ERR! node-gyp -v v3.3.0
> gyp ERR! not ok
> npm ERR! Linux 3.19.8-xen
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "qrcodeine"
> npm ERR! node v4.4.1
> npm ERR! npm  v2.14.20
> npm ERR! code ELIFECYCLE
> npm ERR! qrcodeine@1.0.0 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the qrcodeine@1.0.0 install script 'node-gyp rebuild'.
> npm ERR! This is most likely a problem with the qrcodeine package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs qrcodeine
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!
> npm ERR!     npm owner ls qrcodeine
> npm ERR! There is likely additional logging output above.
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/itnuser/npm-debug.log`

libpng and libqrencode are both installed on each OS. Is there any support for >= 4.x versions of node?

**Comment by kaworu** [comment] 2016-03-29 08:20
Hi @markus138,

Thank you for your report. As stated in the README file, this fork is a port to the 0.12 branch of node, and there is no support at the moment for >= 4.x. We expect to port it soon (around may). We'll leave this issue open until it's done :)

Regards,
Alex.

**Comment by markus138** [comment] 2016-03-29 09:00
thanks for the reply!

**Comment by kaworu** [comment] 2016-07-06 16:10
Hi @markus138 

Port to newer versions of node has just started. I've just pushed a new branch at https://github.com/NetOxygen/node-qrcodeine/tree/nodejs-4.x that is supposed to work with node 4.x. Could you test it? Do you need/want a release on npm in order to do so?

Regards,
Alex.

**Comment by markus138** [comment] 2016-07-06 17:47
Hi, I just tried the current branch, but it seems the `bindings.gyp` can't be loaded:

> Error: Could not locate the bindings file. Tried:
>  → /Users/markusharm/git/testprojects/node-qrcodeine/build/qrcodeine.node
>  → /Users/markusharm/git/testprojects/node-qrcodeine/build/Debug/qrcodeine.node
>  → /Users/markusharm/git/testprojects/node-qrcodeine/build/Release/qrcodeine.node
>  → /Users/markusharm/git/testprojects/node-qrcodeine/out/Debug/qrcodeine.node
>  → /Users/markusharm/git/testprojects/node-qrcodeine/Debug/qrcodeine.node
>  → /Users/markusharm/git/testprojects/node-qrcodeine/out/Release/qrcodeine.node
>  → /Users/markusharm/git/testprojects/node-qrcodeine/Release/qrcodeine.node
>  → /Users/markusharm/git/testprojects/node-qrcodeine/build/default/qrcodeine.node
>  → /Users/markusharm/git/testprojects/node-qrcodeine/compiled/5.1.0/darwin/x64/qrcodeine.node
>     at bindings (/Users/markusharm/git/testprojects/node-qrcodeine/node_modules/bindings/bindings.js:88:9)

dont know it this matters, but my node version is 5.1.0

**Comment by kaworu** [comment] 2016-07-07 08:36
Hi @markus138 

Thank you for getting back so fast ! I was not able to reproduce your error and am not sure what could be the issue. Can you try with this procedure please:

```
git clone "git@github.com:NetOxygen/node-qrcodeine.git"
cd node-qrcodeine
git checkout -b nodejs-4.x origin/nodejs-4.x
npm install
node-gyp configure
node-gyp build
npm test
```

This is working (everything went fine, including all tests passing) for me with Ubuntu 15.10 and various node versions ( v0.12.15, v4.4.7, v5.12.0 and v6.3.0).

**Comment by markus138** [comment] 2016-07-07 08:54
oh thx, I forgot to compile it first -.-
anyway works great now!

**Comment by kaworu** [comment] 2016-07-07 09:10
@markus138 

Great news ! I'll close this issue once merged into master and published on npm.

**Comment by rolinh** [comment] 2016-07-07 18:16
FWIW, I tried with node v6.3.0 and all works fine as well. :smiley:

Edit: oops, I did not see you mentioned that it works fine with v6.3.0 already @kAworu

**Comment by kaworu** [comment] 2016-07-08 07:26
@Rolinh Thanks ! I've only been able to build and run the tests (I did not test further). On that point, the tests need some serious changes (they check the sha1 sum of the resulting png / buffer and it feels hacky).

**Comment by kaworu** [comment] 2016-07-14 14:26
Closing this one since v2.0.0 has been taged and released, see https://www.npmjs.com/package/qrcodeine.

Build is marked as failing for now because meh, the tests sucks and travis-ci libpng and/or libqrencode version must be different. But everything is fine and tests should be fixed at some points.

**Closed as completed by kaworu** 2016-07-14 14:26 UTC
Labels: enhancement

**Comment by kaworu** [comment] 2016-07-14 14:29
@markus138 btw https://github.com/NetOxygen/node-qrcodeine/commit/a9e9c123c4007fbf584e4dbc2e7ea5d93ab6c7e8 made sure that `node-gyp configure build` is called by `npm test` from now on ;)
